---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install apache2 websever ( apt-get install apache2 )
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to start my webserver ( service apache2 start )
    service:
       name: apache2
       state: started
    when: ansible_os_family=="Debian"

  - name: i want to install webserver on RedHat ( yum install httpd)
    dnf:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"

  - name:  i want to start webserver on RedHat ( service httpd start)
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"



 
 